### ISSUE TITLE
Production server issue

### ISSUE THREAD

**Issue by MdAnowarHosen** [dgvai/laravel-nagad#2]
Nagad sandbox is working fine for me. But, After giving my exact Nagad credentials for the production server, I got this error.

`Return value of DGvai\Nagad\NagadGenerator::generatePaymentRequest() must be of the type array, null returned`

My `.env` file:

```
NAGAD_SANDBOX=false
NAGAD_MERHCANT_ID=my_vendor_id
NAGAD_MERHCANT_PHONE=my_marchaint_phone
NAGAD_KEY_PUBLIC=nagad_public_key_here
NAGAD_KEY_PRIVATE=my_nagad_private_key
NAGAD_CALLBACK_URL=nagad.callback 
```

**Comment by dgvai** [comment]
Hello, make sure you have used NAGAD_KEY_PUBLIC=nagad_public_key_here
NAGAD_KEY_PRIVATE=my_nagad_private_key same as production keys

**Comment by AnowarDotDev** [comment]
@dgvai , I just copied and pasted the keys.

**Comment by AnowarDotDev** [comment]
After contacting the Nagad, they give us the Merchant Public / Private Key. Then the problem is gone.
